# Generated by Django 3.2.3 on 2021-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
