# Generated by Django 3.2.3 on 2021-05-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Интересные места'},
        ),
    ]
