# Generated by Django 3.2.3 on 2021-05-26 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210526_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['sort_index'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='sort_index',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Порядковый номер'),
        ),
    ]
