# Generated by Django 3.2.3 on 2021-05-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20210526_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='sort_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
